import React,{useEffect,useMemo,useRef,useState}from'react';
import{openAppDB}from'../utils/db';
import{permanentProductsData}from'../data/permanentProductsData';
import{permanentGalleryPhotosData}from'../data/permanentGalleryPhotosData';
import{generateProductImageAlt}from'../utils/imageSeo';

type Slot='MAIN'|'G0'|'G1'|'G2';
type M={id:string;name:string;data:string;altSr:string;altEn:string;status:'active'|'removed';size:number;original:number;width:number;height:number;createdAt:number};
type DraftProduct={id:string;name:string;nameEn:string;category:string;createdAt:number};
const STORE='admin_media',KEY='admin_image_state_v1',DRAFT_PRODUCTS='admin_product_drafts_v1';
const role=(s:Slot)=>({MAIN:'glavna fotografija',G0:'krupan plan detalja',G1:'otvorena unutrašnjost',G2:'proizvod na modelu'}[s]);
const fallbackAlt=(n:string,s:Slot)=>`${n} — ${role(s)} | Savremeni Koreni`;
const slug=(v:string)=>String(v||'novi-proizvod').toLocaleLowerCase('sr-Latn').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,50);
async function read():Promise<M[]>{const d=await openAppDB();return new Promise((r,j)=>{const q=d.transaction(STORE,'readonly').objectStore(STORE).getAll();q.onsuccess=()=>r(q.result||[]);q.onerror=()=>j(q.error)})}
async function put(m:M){const d=await openAppDB();return new Promise<void>((r,j)=>{const t=d.transaction(STORE,'readwrite');t.objectStore(STORE).put(m);t.oncomplete=()=>r();t.onerror=()=>j(t.error)})}
async function optimise(f:File){const b=await createImageBitmap(f),s=Math.min(1,1600/Math.max(b.width,b.height)),w=Math.max(1,Math.round(b.width*s)),h=Math.max(1,Math.round(b.height*s)),c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d')!.drawImage(b,0,0,w,h);b.close();const z=await new Promise<Blob>((r,j)=>c.toBlob(x=>x?r(x):j(Error('compression')),'image/webp',.82));return new Promise<{data:string,w:number,h:number,size:number}>((r,j)=>{const x=new FileReader();x.onload=()=>r({data:String(x.result),w,h,size:z.size});x.onerror=()=>j(x.error);x.readAsDataURL(z)})}
function loadDrafts():DraftProduct[]{try{return JSON.parse(localStorage.getItem(DRAFT_PRODUCTS)||'[]')}catch{return[]}}
function saveDrafts(v:DraftProduct[]){localStorage.setItem(DRAFT_PRODUCTS,JSON.stringify(v))}
function slotPath(p:any,s:Slot){return s==='MAIN'?p.image||'':p.images?.[s==='G2'?0:s==='G1'?1:2]||''}

export function AdminImageWorkspace(){
 const[media,setMedia]=useState<M[]>([]),[drafts,setDrafts]=useState<DraftProduct[]>([]),[pid,setPid]=useState(String((permanentProductsData as any[])[0]?.id||'')),[slot,setSlot]=useState<Slot>('MAIN'),[sel,setSel]=useState(''),[q,setQ]=useState(''),[msg,setMsg]=useState(''),[newName,setNewName]=useState(''),[newNameEn,setNewNameEn]=useState(''),[newCat,setNewCat]=useState(''),[showNew,setShowNew]=useState(false),[scan,setScan]=useState<Record<string,'OK'|'ERROR'|'TEST'>>({}),[scanning,setScanning]=useState(false),[scanDone,setScanDone]=useState(false);
 const ref=useRef<HTMLInputElement>(null);
 const products=useMemo(()=>[...(permanentProductsData as any[]),...drafts], [drafts]);
 const p=products.find(x=>x.id===pid),m=media.find(x=>x.id===sel);
 useEffect(()=>{read().then(setMedia).catch(()=>{});setDrafts(loadDrafts())},[]);
 const active=media.filter(x=>x.status==='active'),removed=media.filter(x=>x.status==='removed');
 const filtered=active.filter(x=>x.name.toLowerCase().includes(q.toLowerCase()));
 const add=async(fs:FileList|null)=>{if(!fs)return;let count=0;for(const f of Array.from(fs)){if(!f.type.startsWith('image/'))continue;try{const z=await optimise(f),id='am-'+Date.now()+'-'+Math.random().toString(36).slice(2,8),base=f.name.replace(/\.[^.]+$/,'');const x:M={id,name:slug(base)+'.webp',data:z.data,altSr:fallbackAlt(p?.name||base,slot),altEn:fallbackAlt(p?.nameEn||p?.name||base,slot),status:'active',size:z.size,original:f.size,width:z.w,height:z.h,createdAt:Date.now()};await put(x);setMedia(v=>[x,...v]);setSel(x.id);count++}catch{setMsg('Jedna ili više slika nije mogla biti optimizovana. Proverite format fajla.')}}setMsg(count?`${count} slika dodato. Originali nisu menjani; Admin čuva optimizovane WEBP kopije.`:'Nema dodatih slika.')};
 const createDraft=()=>{const n=newName.trim();if(!n){setMsg('Unesite naziv novog proizvoda.');return}const id='draft-'+slug(n)+'-'+Date.now();const d={id,name:n,nameEn:newNameEn.trim()||n,category:newCat.trim()||'Nova kolekcija',createdAt:Date.now()};const next=[...drafts,d];saveDrafts(next);setDrafts(next);setPid(id);setShowNew(false);setNewName('');setNewNameEn('');setNewCat('');setMsg('Novi proizvod je napravljen samo kao DRAFT. Nije objavljen niti menja 47 postojećih proizvoda.')};
 const assign=()=>{if(!m||!p)return;const a=JSON.parse(localStorage.getItem(KEY)||'{}');a[pid]={...(a[pid]||{}),[slot]:m.id};localStorage.setItem(KEY,JSON.stringify(a));setMsg(`${p.name}: ${slot} → ${m.name}`)}; 
 const unassign=()=>{const a=JSON.parse(localStorage.getItem(KEY)||'{}');if(a[pid])delete a[pid][slot];localStorage.setItem(KEY,JSON.stringify(a));setMsg('Veza uklonjena; fizička slika ostaje u biblioteci.')};
 const remove=async()=>{if(!m)return;const x={...m,status:'removed' as const};await put(x);setMedia(v=>v.map(y=>y.id===x.id?x:y));setMsg('Uklonjena iz aktivnog prikaza, ali ostaje u biblioteci.')};
 const restore=async()=>{if(!m)return;const x={...m,status:'active' as const};await put(x);setMedia(v=>v.map(y=>y.id===x.id?x:y));setMsg('Slika je vraćena u aktivnu biblioteku.')};
 const ai=async()=>{if(!m)return;try{const r=await generateProductImageAlt({imageUrl:m.data,productNameSr:p?.name||m.name,productNameEn:p?.nameEn||p?.name||m.name,keywords:[p?.category,...(p?.materials||[])].filter(Boolean),imageRole:slot==='MAIN'?'main':slot==='G0'?'closeup':slot==='G1'?'interior':'model',apiKey:localStorage.getItem('koreni_gemini_api_key')||''});const x={...m,altSr:r.altSr,altEn:r.altEn};await put(x);setMedia(v=>v.map(y=>y.id===x.id?x:y));setMsg(r.source==='vision'?'AI Vision ALT gotov — pregledajte pre odobrenja.':'Sigurni ALT fallback gotov — pregledajte pre odobrenja.')}catch{setMsg('AI ALT trenutno nije dostupan; slika nije menjana.')}};
 const updateAlt=async(field:'altSr'|'altEn',value:string)=>{if(!m)return;const x={...m,[field]:value};await put(x);setMedia(v=>v.map(y=>y.id===x.id?x:y))};
 const scanUrls=useMemo(()=>{const rows:(string[])[]=[];(permanentGalleryPhotosData as any[]).forEach(x=>{if(x.imageUrl)rows.push([x.id,x.imageUrl])});return rows},[]);
 const runScan=async()=>{if(scanning)return;setScanning(true);setScanDone(false);const result:Record<string,'OK'|'ERROR'|'TEST'>={};let i=0;const worker=async()=>{while(i<scanUrls.length){const n=i++,row=scanUrls[n];result[row[0]]='TEST';await new Promise<void>(resolve=>{const im=new Image();const timer=window.setTimeout(()=>{result[row[0]]='ERROR';resolve()},7000);im.onload=()=>{clearTimeout(timer);result[row[0]]='OK';resolve()};im.onerror=()=>{clearTimeout(timer);result[row[0]]='ERROR';resolve()};im.src=row[1]})}};await Promise.all(Array.from({length:6},worker));setScan({...result});setScanDone(true);setScanning(false);setMsg('Provera javnih URL-ova završena. Ovo je dijagnostika — nijedna slika nije menjana.')};
 const scanOk=Object.values(scan).filter(x=>x==='OK').length,scanErr=Object.values(scan).filter(x=>x==='ERROR').length;
 return <section className="rounded-2xl bg-white border-2 border-[#9e3e26] p-5 mb-6">
  <div className="flex flex-wrap justify-between gap-3 mb-4"><div><div className="text-[10px] font-bold tracking-[.18em] text-[#9e3e26]">IMAGE WORKSPACE</div><h2 className="text-2xl font-bold">Slike — funkcionalni deo</h2><p className="text-xs text-gray-600">Dodaj • novi proizvod • kompresuj • rasporedi • ALT • ukloni/vrati</p></div><div className="flex gap-2"><button onClick={()=>setShowNew(v=>!v)} className="px-4 py-2 rounded-xl border border-[#9e3e26] text-[#9e3e26] text-xs font-bold">+ NOVI PROIZVOD</button><button onClick={()=>ref.current?.click()} className="px-4 py-2 rounded-xl bg-[#9e3e26] text-white text-xs font-bold">+ DODAJ SLIKE</button><input ref={ref} hidden type="file" accept="image/*" multiple onChange={e=>add(e.target.files)}/></div></div>
  {showNew&&<div className="mb-4 p-4 rounded-xl bg-[#f7f3ed] border border-[#d8cec1] grid md:grid-cols-4 gap-2"><input value={newName} onChange={e=>setNewName(e.target.value)} placeholder="Naziv proizvoda SR *" className="border rounded-lg p-2 text-xs"/><input value={newNameEn} onChange={e=>setNewNameEn(e.target.value)} placeholder="Naziv proizvoda EN" className="border rounded-lg p-2 text-xs"/><input value={newCat} onChange={e=>setNewCat(e.target.value)} placeholder="Kategorija" className="border rounded-lg p-2 text-xs"/><button onClick={createDraft} className="rounded-lg bg-[#241d19] text-white text-xs font-bold">KREIRAJ DRAFT</button></div>}
  <div className="grid lg:grid-cols-3 gap-4">
   <div>
    <div className="grid grid-cols-2 gap-2 mb-2"><select value={pid} onChange={e=>setPid(e.target.value)} className="border rounded-lg p-2 text-xs">{products.map(x=><option key={x.id} value={x.id}>{x.name}{String(x.id).startsWith('draft-')?' • DRAFT':''}</option>)}</select><select value={slot} onChange={e=>setSlot(e.target.value as Slot)} className="border rounded-lg p-2 text-xs"><option>MAIN</option><option>G0</option><option>G1</option><option>G2</option></select></div>
    <input value={q} onChange={e=>setQ(e.target.value)} placeholder="Pretraga biblioteke" className="border rounded-lg p-2 text-xs w-full mb-2"/>
    <div className="text-[10px] text-gray-500 mb-2">Aktivne: {active.length} • Uklonjene: {removed.length} • Ukupno Admin: {media.length}</div>
    <div className="grid grid-cols-3 gap-2 max-h-80 overflow-auto">{filtered.map(x=><button key={x.id} onClick={()=>setSel(x.id)} className={sel===x.id?'border-2 border-[#9e3e26] p-1 rounded-lg':'border p-1 rounded-lg'}><img src={x.data} alt={x.altSr} className="aspect-square w-full object-cover rounded" loading="lazy"/><span className="text-[8px] block truncate">{x.name}</span></button>)}</div>
   </div>
   <div className="lg:col-span-2">{m?<><img src={m.data} alt={m.altSr} width={m.width} height={m.height} className="w-full max-h-56 object-contain bg-[#faf8f4] rounded-xl"/><div className="text-[10px] mt-2">{m.width}×{m.height} • {Math.round(m.size/1024)} KB • original {Math.round(m.original/1024)} KB • ${m.original?Math.max(0,Math.round((1-m.size/m.original)*100)):0}% manje</div><input value={m.altSr} onChange={e=>updateAlt('altSr',e.target.value)} placeholder="ALT SR — prirodan opis fotografije" className="border rounded-lg p-2 text-xs w-full mt-2"/><input value={m.altEn} onChange={e=>updateAlt('altEn',e.target.value)} placeholder="ALT EN — natural image description" className="border rounded-lg p-2 text-xs w-full mt-2"/><div className="flex flex-wrap gap-2 mt-2"><button onClick={ai} className="border rounded-lg px-3 py-2 text-xs font-bold">AI ALT</button><button onClick={assign} className="bg-[#9e3e26] text-white rounded-lg px-3 py-2 text-xs font-bold">POSTAVI {slot}</button><button onClick={unassign} className="border rounded-lg px-3 py-2 text-xs">ODVEŽI</button>{m.status==='active'?<button onClick={remove} className="border border-red-300 text-red-700 rounded-lg px-3 py-2 text-xs font-bold">UKLONI SA SAJTA</button>:<button onClick={restore} className="border border-green-300 text-green-700 rounded-lg px-3 py-2 text-xs font-bold">VRATI NA SAJT</button>}</div></>:<div className="text-xs text-gray-500 p-5">Izaberite sliku iz biblioteke.</div>}{msg&&<div className="mt-3 p-3 bg-[#f7f3ed] rounded-lg text-xs">{msg}</div>}</div>
  </div>
  <div className="mt-5 p-4 rounded-xl border border-[#d8cec1] bg-[#fbfaf8]"><div className="flex flex-wrap justify-between gap-2 items-center"><div><b className="text-sm">MEDIA INTEGRITY — provera slika koje se ne otvaraju</b><div className="text-[10px] text-gray-500">Proverava stvarne javne image URL-ove iz galerijskog indeksa. Nema izmene podataka.</div></div><button onClick={runScan} disabled={scanning} className="px-4 py-2 rounded-lg bg-[#241d19] text-white text-xs font-bold disabled:opacity-50">{scanning?'PROVERAVAM…':'PROVERI SVE JAVNE SLIKE'}</button></div>{scanDone&&<div className="mt-3 grid grid-cols-3 gap-2 text-xs"><div className="p-2 rounded bg-green-50 text-green-800"><b>{scanOk}</b> otvara se</div><div className="p-2 rounded bg-red-50 text-red-800"><b>{scanErr}</b> greška</div><div className="p-2 rounded bg-gray-50"><b>{scanUrls.length}</b> ukupno provereno</div></div>}{scanErr>0&&<div className="mt-3 max-h-48 overflow-auto text-[10px] border rounded-lg p-2">{scanUrls.filter(x=>scan[x[0]]==='ERROR').map(x=><div key={x[0]} className="py-1 border-b">{x[0]} — {x[1]}</div>)}</div>}</div>
  <div className="mt-4 text-[10px] text-gray-500"><b>SEO/performanse:</b> original ostaje za biblioteku; upload dobija optimizovanu WEBP kopiju, čuvaju se dimenzije radi sprečavanja CLS, a produkcioni publish treba da generiše javni crawlable URL, responsive varijante i ImageObject/Product structured data. Cloudflare može dodatno isporučivati WebP/AVIF i resize varijante na CDN-u kada se odgovarajuća image infrastruktura uključi. </div>
 </section>
}