import React,{useEffect,useMemo,useRef,useState}from'react';
import{permanentProductsData}from'../data/permanentProductsData';
import{permanentGalleryPhotosData}from'../data/permanentGalleryPhotosData';
import{publicCustomProductsManifest}from'../data/publicCustomProductsManifest';
import{generateProductImageAlt}from'../utils/imageSeo';

type Slot='MAIN'|'G0'|'G1'|'G2';
type Filter='all'|'used'|'unused'|'removed'|'new';
type LibraryCategory='Kolekcije'|'Galerija'|'Blog'|'Landing/Homepage'|'Logo/brand'|'Ostalo';
type Asset={id:string;name:string;path:string;data?:string;altSr:string;altEn:string;status:'active'|'removed';source:'repository'|'upload';category:LibraryCategory;size?:number;original?:number;width?:number;height?:number;createdAt:number};
type Draft={id:string;name:string;nameEn:string;category:string;createdAt:number;removed?:boolean};
const ASSET_KEY='admin2_media_v2',DRAFT_KEY='admin2_product_drafts_v2',ASSIGN_KEY='admin2_assignments_v2',HISTORY_KEY='admin2_history_v2';
const slots:Slot[]=['MAIN','G0','G1','G2'];
const role=(s:Slot)=>({MAIN:'glavna fotografija proizvoda',G0:'krupan plan detalja',G1:'otvorena unutrašnjost proizvoda',G2:'proizvod na modelu'}[s]);
const slug=(v:string)=>String(v||'').toLocaleLowerCase('sr-Latn').normalize('NFD').replace(/[\\u0300-\\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,60);
const readJson=<T,>(k:string,f:T):T=>{try{return JSON.parse(localStorage.getItem(k)||'null')??f}catch{return f}};
const writeJson=(k:string,v:any)=>localStorage.setItem(k,JSON.stringify(v));
const slotPath=(p:any,s:Slot)=>s==='MAIN'?p.image||'':p.images?.[s==='G2'?0:s==='G1'?1:2]||'';
const normalize=(v:string)=>String(v||'').replace(/^\/+/, '/');
const classifyRepoAsset=(path:string,productPaths:Set<string>,galleryPaths:Set<string>):LibraryCategory=>{const p=normalize(path).toLocaleLowerCase('sr-Latn');if(productPaths.has(normalize(path)))return'Kolekcije';if(galleryPaths.has(normalize(path)))return'Galerija';if(/(^|[\\/])blog([\\/]|[-_])/i.test(p)||/(^|[-_])blog[-_]/i.test(p))return'Blog';if(/landing|homepage|home-page|hero|banner|target/i.test(p))return'Landing/Homepage';if(/logo|emblem|brand/i.test(p))return'Logo/brand';return'Ostalo'};

async function optimise(file:File){const b=await createImageBitmap(file),scale=Math.min(1,1600/Math.max(b.width,b.height)),w=Math.max(1,Math.round(b.width*scale)),h=Math.max(1,Math.round(b.height*scale)),c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d')!.drawImage(b,0,0,w,h);b.close();const blob=await new Promise<Blob>((res,rej)=>c.toBlob(x=>x?res(x):rej(Error('compression')),'image/webp',.82));return await new Promise<{data:string;w:number;h:number;size:number}>((res,rej)=>{const r=new FileReader();r.onload=()=>res({data:String(r.result),w,h,size:blob.size});r.onerror=()=>rej(r.error);r.readAsDataURL(blob)})}

export function AdminImageWorkspace(){
 const [uploads,setUploads]=useState<Asset[]>(()=>readJson<Asset[]>(ASSET_KEY,[]));
 const [drafts,setDrafts]=useState<Draft[]>(()=>readJson<Draft[]>(DRAFT_KEY,[]));
 const [assignments,setAssignments]=useState<Record<string,Partial<Record<Slot,string>>>>(()=>readJson(ASSIGN_KEY,{}));
 const [removed,setRemoved]=useState<Record<string,boolean>>(()=>readJson('admin2_removed_media_v2',{}));
 const [productRemoved,setProductRemoved]=useState<Record<string,boolean>>(()=>readJson('admin2_removed_products_v2',{}));
 const [history,setHistory]=useState<any[]>(()=>readJson(HISTORY_KEY,[]));
 const [filter,setFilter]=useState<Filter>('all'),[category,setCategory]=useState<LibraryCategory|'Sve'>('Sve'),[q,setQ]=useState(''),[selected,setSelected]=useState<string>(''),[productId,setProductId]=useState(String((permanentProductsData as any[])[0]?.id||'')),[slot,setSlot]=useState<Slot>('MAIN');
 const [showNew,setShowNew]=useState(false),[newName,setNewName]=useState(''),[newNameEn,setNewNameEn]=useState(''),[newCat,setNewCat]=useState('');
 const [msg,setMsg]=useState(''),[scan,setScan]=useState<Record<string,'OK'|'ERROR'>>({}),[scanning,setScanning]=useState(false),[preview,setPreview]=useState<Asset|null>(null),[altBusy,setAltBusy]=useState(false);
 const fileRef=useRef<HTMLInputElement>(null);

 const canonicalPaths=useMemo(()=>{const s=new Set<string>();(permanentProductsData as any[]).forEach(p=>slots.forEach(x=>{const v=slotPath(p,x);if(v)s.add(normalize(v))}));return s},[]);
 const galleryPaths=useMemo(()=>new Set((permanentGalleryPhotosData as any[]).map(x=>normalize(x.imageUrl)).filter(Boolean)),[]);
 const repoAssets=useMemo<Asset[]>(()=>publicCustomProductsManifest.map((f:string)=>{const path='/custom_products/'+f;return{id:'repo-'+f,name:f,path,altSr:f,altEn:f,status:removed['repo-'+f]?'removed':'active',source:'repository',category:classifyRepoAsset(path,canonicalPaths,galleryPaths),createdAt:0}}),[removed,canonicalPaths,galleryPaths]);
 const assets=useMemo(()=>[...uploads.map(a=>({...a,category:a.category||'Ostalo'})),...repoAssets],[uploads,repoAssets]);
 const products=useMemo(()=>[...(permanentProductsData as any[]),...drafts],[drafts]);
 const activeProducts=useMemo(()=>products.filter(p=>!productRemoved[p.id]),[products,productRemoved]);
 const selectedAsset=assets.find(a=>a.id===selected);
 const product=products.find(p=>p.id===productId);

 const usage=useMemo(()=>{const map:Record<string,{productId:string;productName:string;slot:Slot}[]>= {}; (permanentProductsData as any[]).forEach(p=>slots.forEach(s=>{const path=slotPath(p,s);if(path){const a=repoAssets.find(x=>x.path===path);if(a)(map[a.id]??=[]).push({productId:p.id,productName:p.name,slot:s})}})); Object.entries(assignments).forEach(([pid,ss])=>Object.entries(ss).forEach(([s,id])=>{if(id){const p=products.find(x=>x.id===pid);if(p)(map[id]??=[]).push({productId:pid,productName:p.name,slot:s as Slot})}}));return map},[repoAssets,assignments,products]);
 const filtered=useMemo(()=>{const term=q.trim().toLocaleLowerCase('sr-Latn');return assets.filter(a=>{const used=(usage[a.id]||[]).length>0,rem=a.status==='removed';const ok=filter==='all'||(filter==='used'&&used)||(filter==='unused'&&!used&&!rem)||(filter==='removed'&&rem)||(filter==='new'&&a.source==='upload');const catOk=category==='Sve'||a.category===category;const hay=(a.name+' '+a.path+' '+(usage[a.id]||[]).map(x=>x.productName+' '+x.slot).join(' ')).toLocaleLowerCase('sr-Latn');return ok&&catOk&&(!term||hay.includes(term))})},[assets,filter,category,q,usage]);
 const counts=useMemo(()=>({all:assets.length,used:assets.filter(a=>(usage[a.id]||[]).length).length,unused:assets.filter(a=>!(usage[a.id]||[]).length&&a.status==='active').length,removed:assets.filter(a=>a.status==='removed').length,new:uploads.length}),[assets,uploads,usage]);
 const categoryCounts=useMemo(()=>{const out=Object.fromEntries(['Kolekcije','Galerija','Blog','Landing/Homepage','Logo/brand','Ostalo'].map(x=>[x,0])) as Record<LibraryCategory,number>;assets.forEach(a=>out[a.category]++);return out},[assets]);
 const pushHistory=(label:string)=>{const h=[...history,{label,time:new Date().toISOString(),assignments,removed,productRemoved}].slice(-30);setHistory(h);writeJson(HISTORY_KEY,h)};
 const changeAssignment=(s:Slot,id:string|undefined)=>{pushHistory('Promena dodele slike');const next={...assignments,[productId]:{...(assignments[productId]||{})}};if(id)next[productId][s]=id;else delete next[productId][s];setAssignments(next);writeJson(ASSIGN_KEY,next);setMsg(`${product?.name||productId}: ${s} ${id?'postavljen':'odvezan'} — fizički fajl nije menjan.`)};
 const softRemove=()=>{if(!selectedAsset)return;pushHistory('Uklanjanje slike iz aktivne biblioteke');const next={...removed,[selectedAsset.id]:true};setRemoved(next);writeJson('admin2_removed_media_v2',next);setMsg('Slika je uklonjena samo iz aktivnog prikaza. Fizički fajl ostaje sačuvan.')};
 const restore=()=>{if(!selectedAsset)return;pushHistory('Vraćanje slike');const next={...removed};delete next[selectedAsset.id];setRemoved(next);writeJson('admin2_removed_media_v2',next);setMsg('Slika je vraćena u aktivnu biblioteku.')};
 const createDraft=()=>{if(!newName.trim()){setMsg('Naziv proizvoda je obavezan.');return}const d={id:'draft-'+slug(newName)+'-'+Date.now(),name:newName.trim(),nameEn:newNameEn.trim()||newName.trim(),category:newCat.trim()||'Nova kolekcija',createdAt:Date.now()};const n=[...drafts,d];setDrafts(n);writeJson(DRAFT_KEY,n);setProductId(d.id);setShowNew(false);setNewName('');setNewNameEn('');setNewCat('');setMsg('Novi proizvod je DRAFT; nije dodat u javnu Kolekciju.')};
 const toggleProduct=()=>{const next={...productRemoved};next[productId]=!next[productId];setProductRemoved(next);writeJson('admin2_removed_products_v2',next);setMsg(next[productId]?'Proizvod je označen za uklanjanje iz javne Kolekcije.':'Proizvod je vraćen u aktivni spisak. Ovo je reverzibilni Admin nacrt.')};
 const addFiles=async(fs:FileList|null)=>{if(!fs)return;const next:Asset[]=[];for(const f of Array.from(fs)){if(!f.type.startsWith('image/'))continue;try{const z=await optimise(f),id='upload-'+Date.now()+'-'+Math.random().toString(36).slice(2,8);next.push({id,name:slug(f.name.replace(/\\.[^.]+$/,''))+'.webp',path:'',data:z.data,altSr:'',altEn:'',status:'active',source:'upload',category:'Ostalo',size:z.size,original:f.size,width:z.w,height:z.h,createdAt:Date.now()})}catch{}}if(next.length){const n=[...next,...uploads];setUploads(n);writeJson(ASSET_KEY,n);setSelected(next[0].id);setMsg(`${next.length} novih slika je kompresovano i sačuvano kao Admin DRAFT. Za javni sajt potreban je publish korak.`)}};
 const updateAlt=(field:'altSr'|'altEn',value:string)=>{if(!selectedAsset||selectedAsset.source!=='upload')return;const n=uploads.map(a=>a.id===selectedAsset.id?{...a,[field]:value}:a);setUploads(n);writeJson(ASSET_KEY,n)};
 const aiAlt=async()=>{if(!selectedAsset||!product)return;setAltBusy(true);try{const r=await generateProductImageAlt({imageUrl:selectedAsset.data||selectedAsset.path,productNameSr:product.name,productNameEn:product.nameEn||product.name,keywords:[product.category,...(product.materials||[]),...(product.craftTechniques||[])].filter(Boolean),imageRole:slot==='MAIN'?'main':slot==='G0'?'closeup':slot==='G1'?'interior':'model',apiKey:localStorage.getItem('koreni_gemini_api_key')||''});const n=uploads.map(a=>a.id===selectedAsset.id?{...a,altSr:r.altSr,altEn:r.altEn}:a);setUploads(n);writeJson(ASSET_KEY,n);setMsg('AI ALT predlog je generisan; pregledajte ga pre publish-a.')}catch{setMsg('AI ALT nije dostupan; ništa nije obrisano.')}finally{setAltBusy(false)}};
 const undo=()=>{const last=history.at(-1);if(!last){setMsg('Nema istorije.');return}setAssignments(last.assignments||{});setRemoved(last.removed||{});setProductRemoved(last.productRemoved||{});writeJson(ASSIGN_KEY,last.assignments||{});writeJson('admin2_removed_media_v2',last.removed||{});writeJson('admin2_removed_products_v2',last.productRemoved||{});setHistory(history.slice(0,-1));writeJson(HISTORY_KEY,history.slice(0,-1));setMsg('Poslednja Admin promena je vraćena.')};
 const runScan=async()=>{if(scanning)return;setScanning(true);const paths=repoAssets.map(a=>a.path),out:Record<string,'OK'|'ERROR'>={};let i=0;const worker=async()=>{while(i<paths.length){const p=paths[i++];await new Promise<void>(res=>{const im=new Image(),t=window.setTimeout(()=>{out[p]='ERROR';res()},6000);im.onload=()=>{clearTimeout(t);out[p]='OK';res()};im.onerror=()=>{clearTimeout(t);out[p]='ERROR';res()};im.src=p})}};await Promise.all(Array.from({length:8},worker));setScan(out);setScanning(false);setMsg('Provera javnih URL-ova završena. Nema upisa u proizvode ni fajlove.')};
 const integrity=useMemo(()=>{const paths=new Set(repoAssets.map(a=>a.path));const refs=(permanentProductsData as any[]).flatMap(p=>slots.map(s=>({p:p.name,s,path:slotPath(p,s)})));return{physical:repoAssets.length,slots:refs.length,missing:refs.filter(x=>x.path&&!paths.has(x.path)).length,empty:refs.filter(x=>!x.path).length,errors:Object.values(scan).filter(x=>x==='ERROR').length}},[repoAssets,scan]);
 const assigned=assignments[productId]||{};
 return <section className="rounded-2xl bg-white border-2 border-[#9e3e26] p-5 mb-6">
  <div className="flex flex-wrap justify-between gap-3 mb-4"><div><div className="text-[10px] font-bold tracking-[.18em] text-[#9e3e26]">IMAGE WORKSPACE · FAZA 2E–2L</div><h2 className="text-2xl font-bold">Media Library + Image Manager</h2><p className="text-xs text-gray-600">504 fizičkih fajlova • vizuelni pregled • 47×4 slotova • upload • ALT • ukloni/vrati • istorija</p></div><div className="flex gap-2"><button onClick={()=>setShowNew(!showNew)} className="px-4 py-2 rounded-xl border border-[#9e3e26] text-[#9e3e26] text-xs font-bold">+ NOVI PROIZVOD</button><button onClick={()=>fileRef.current?.click()} className="px-4 py-2 rounded-xl bg-[#9e3e26] text-white text-xs font-bold">+ DODAJ SLIKE</button><input ref={fileRef} hidden type="file" accept="image/*" multiple onChange={e=>addFiles(e.target.files)}/></div></div>
  {showNew&&<div className="mb-4 p-4 rounded-xl bg-[#f7f3ed] border grid md:grid-cols-4 gap-2"><input value={newName} onChange={e=>setNewName(e.target.value)} placeholder="Naziv SR *" className="border rounded-lg p-2 text-xs"/><input value={newNameEn} onChange={e=>setNewNameEn(e.target.value)} placeholder="Naziv EN" className="border rounded-lg p-2 text-xs"/><input value={newCat} onChange={e=>setNewCat(e.target.value)} placeholder="Kategorija" className="border rounded-lg p-2 text-xs"/><button onClick={createDraft} className="rounded-lg bg-[#241d19] text-white text-xs font-bold">KREIRAJ DRAFT</button></div>}
  <div className="grid lg:grid-cols-[1.25fr_.9fr] gap-5">
   <div>
    <div className="mb-3 flex flex-wrap gap-2 items-center"><b className="text-xs mr-1">KATEGORIJA:</b>{(['Sve','Kolekcije','Galerija','Blog','Landing/Homepage','Logo/brand','Ostalo'] as const).map(cat=><button key={cat} onClick={()=>setCategory(cat)} className={category===cat?'px-3 py-2 rounded-lg bg-[#9e3e26] text-white text-xs font-bold':'px-3 py-2 rounded-lg border text-xs'}>{cat} <span className="opacity-70">({cat==='Sve'?counts.all:categoryCounts[cat]})</span></button>)}</div>
    <div className="flex flex-wrap gap-2 mb-3">{(['all','used','unused','removed','new'] as Filter[]).map(f=><button key={f} onClick={()=>setFilter(f)} className={filter===f?'px-3 py-2 rounded-lg bg-[#241d19] text-white text-xs font-bold':'px-3 py-2 rounded-lg border text-xs'}>{f==='all'?'SVE':f==='used'?'KORIŠĆENE':f==='unused'?'NEPOVEZANE':f==='removed'?'UKLONJENE':'NOVI UPLOAD'} <span className="opacity-70">({counts[f]})</span></button>)}</div>
    <input value={q} onChange={e=>setQ(e.target.value)} placeholder="Pretraži fajl, putanju, proizvod ili slot…" className="border rounded-xl p-3 text-xs w-full mb-3"/>
    <div className="text-[10px] text-gray-500 mb-2">Biblioteka: <b>{assets.length} / 504</b> • Prikaz {filtered.length} • Korišćene {counts.used} • Nepovezane {counts.unused} • Uklonjene {counts.removed}</div>
    <div className="grid grid-cols-3 sm:grid-cols-4 md:grid-cols-5 gap-2 max-h-[560px] overflow-auto pr-1">{filtered.map(a=><button key={a.id} onClick={()=>setSelected(a.id)} className={selected===a.id?'border-2 border-[#9e3e26] rounded-xl p-1 bg-white':'border rounded-xl p-1 bg-white'}><div className="aspect-square bg-gray-100 rounded-lg overflow-hidden">{a.data?<img src={a.data} className="w-full h-full object-cover" alt={a.altSr||a.name}/>:<img src={a.path} className="w-full h-full object-cover" alt={a.altSr||a.name} loading="lazy"/>}</div><div className="text-[8px] font-bold truncate mt-1">{a.name}</div><div className="text-[8px] text-gray-500 truncate">{(usage[a.id]||[]).map(x=>x.slot).join(' • ')||'NEPOVEZANA'}</div></button>)}</div>
   </div>
   <div className="space-y-4">
    <div className="rounded-xl border p-4"><div className="font-bold text-sm mb-2">1. PROIZVOD + SLOT</div><div className="grid grid-cols-2 gap-2"><select value={productId} onChange={e=>setProductId(e.target.value)} className="border rounded-lg p-2 text-xs">{activeProducts.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select value={slot} onChange={e=>setSlot(e.target.value as Slot)} className="border rounded-lg p-2 text-xs">{slots.map(s=><option key={s}>{s}</option>)}</select></div><div className="text-[10px] text-gray-500 mt-2">MAIN = cela fotografija • G0 = detalj • G1 = otvoren proizvod • G2 = model</div><div className="grid grid-cols-4 gap-1 mt-3">{slots.map(s=>{const id=assigned[s];const a=assets.find(x=>x.id===id)||assets.find(x=>x.path===slotPath(product,s));return <button key={s} onClick={()=>setSlot(s)} className="border rounded-lg p-1 text-left"><div className="text-[8px] font-bold">{s}</div><div className="aspect-square bg-gray-100 rounded overflow-hidden">{a&&(a.data?<img src={a.data} className="w-full h-full object-cover"/>:<img src={a.path} className="w-full h-full object-cover"/>)}</div></button>})}</div>{selectedAsset&&<div className="flex flex-wrap gap-2 mt-3"><button onClick={()=>changeAssignment(slot,selectedAsset.id)} className="px-3 py-2 rounded-lg bg-[#9e3e26] text-white text-xs font-bold">POSTAVI {slot}</button><button onClick={()=>changeAssignment(slot,undefined)} className="px-3 py-2 rounded-lg border text-xs">ODVEŽI</button></div>}</div>
    {selectedAsset?<div className="rounded-xl border p-4"><div className="flex justify-between gap-2"><div className="font-bold text-sm truncate">{selectedAsset.name}</div><button onClick={()=>setPreview(selectedAsset)} className="text-xs underline">VELIKI PREGLED</button></div><div className="aspect-[4/3] bg-gray-100 rounded-xl overflow-hidden mt-2">{selectedAsset.data?<img src={selectedAsset.data} className="w-full h-full object-contain"/>:<img src={selectedAsset.path} className="w-full h-full object-contain"/>}</div><div className="text-[9px] break-all mt-2">{selectedAsset.path||'ADMIN UPLOAD — još nema javnu putanju'}</div>{selectedAsset.source==='upload'&&<><input value={selectedAsset.altSr} onChange={e=>updateAlt('altSr',e.target.value)} placeholder="ALT SR" className="border rounded-lg p-2 text-xs w-full mt-2"/><input value={selectedAsset.altEn} onChange={e=>updateAlt('altEn',e.target.value)} placeholder="ALT EN" className="border rounded-lg p-2 text-xs w-full mt-2"/><button disabled={altBusy} onClick={aiAlt} className="mt-2 px-3 py-2 rounded-lg border text-xs font-bold">{altBusy?'AI ANALIZA…':'AI ALT PREDLOG'}</button></>}<div className="flex flex-wrap gap-2 mt-3">{selectedAsset.status==='active'?<button onClick={softRemove} className="px-3 py-2 rounded-lg border border-red-300 text-red-700 text-xs font-bold">UKLONI SA SAJTA</button>:<button onClick={restore} className="px-3 py-2 rounded-lg border border-green-300 text-green-700 text-xs font-bold">VRATI</button>}<button onClick={undo} className="px-3 py-2 rounded-lg border text-xs">↶ VRATI POSLEDNJU IZMENU</button></div><div className="mt-3 text-[10px] text-gray-500">Fizičko brisanje fajla nije dozvoljeno u ovoj fazi.</div></div>:<div className="rounded-xl border p-6 text-xs text-gray-500">Izaberite fotografiju iz biblioteke.</div>}
    <div className="rounded-xl border p-4"><div className="font-bold text-sm">2. PROIZVOD STATUS</div><div className="text-[10px] text-gray-500 mb-2">Označavanje je reverzibilni Admin nacrt; ne menja canonical 47 dok se ne uradi publish.</div><button onClick={toggleProduct} className={productRemoved[productId]?'px-3 py-2 rounded-lg border border-green-300 text-green-700 text-xs font-bold':'px-3 py-2 rounded-lg border border-red-300 text-red-700 text-xs font-bold'}>{productRemoved[productId]?'VRATI U KOLEKCIJE':'OZNAČI ZA UKLANJANJE IZ KOLEKCIJE'}</button></div>
   </div>
  </div>
  <div className="mt-5 rounded-xl border p-4 bg-[#fbfaf8]"><div className="flex flex-wrap justify-between gap-2 items-center"><div><b>VALIDACIJA 504 / 188</b><div className="text-[10px] text-gray-500">{integrity.physical} fizičkih fajlova • {integrity.slots} slotova • {integrity.missing} nedostajućih putanja • {integrity.empty} praznih slotova • {integrity.errors} URL grešaka</div></div><button onClick={runScan} disabled={scanning} className="px-4 py-2 rounded-lg bg-[#241d19] text-white text-xs font-bold">{scanning?'PROVERAVAM…':'PROVERI SVE JAVNE URL-ove'}</button></div>{msg&&<div className="mt-3 p-3 rounded-lg bg-white border text-xs">{msg}</div>}{integrity.errors>0&&<div className="mt-2 text-[10px] text-red-700">{Object.entries(scan).filter(([,v])=>v==='ERROR').map(([p])=><div key={p}>{p}</div>)}</div>}</div>
  <div className="mt-3 p-3 rounded-xl bg-amber-50 border border-amber-200 text-[10px] text-amber-900"><b>VAŽNO:</b> repo slike su READ ONLY izvor istine. Admin izmene su Draft u browseru; upload slike i lokalne veze ne postaju javne dok se ne uvede potvrđeni publish adapter ka GitHub/Cloudflare. Nema IndexedDB i nema fizičkog brisanja.</div>
  {preview&&<div className="fixed inset-0 z-[80] bg-black/80 p-4 flex items-center justify-center" onClick={()=>setPreview(null)}><div className="bg-white rounded-2xl max-w-5xl w-full p-4" onClick={e=>e.stopPropagation()}><div className="flex justify-between mb-3"><b>{preview.name}</b><button onClick={()=>setPreview(null)}>Zatvori</button></div>{preview.data?<img src={preview.data} className="w-full max-h-[75vh] object-contain"/>:<img src={preview.path} className="w-full max-h-[75vh] object-contain"/>}<div className="text-xs break-all mt-2">{preview.path}</div><div className="text-xs mt-2">Veze: {(usage[preview.id]||[]).map(x=>x.productName+' — '+x.slot).join(' • ')||'nema'}</div></div></div>}
 </section>
}
